# Generated by Django 5.2.4 on 2025-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('application_tips', 'Application Tips'), ('scholarship', 'Scholarship'), ('financial_aid', 'Financial Aid'), ('test_prep', 'Test Preparation'), ('essay_help', 'Essay Help'), ('deadline', 'Important Deadline')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('is_priority', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_education', models.TextField()),
                ('skills_needed', models.TextField()),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('job_outlook', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('campaign_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('study_abroad', 'Study Abroad'), ('research', 'Research Opportunity'), ('club', 'Student Club/Organization'), ('event', 'Campus Event')], max_length=20)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('doctorate', 'Doctorate'), ('certificate', 'Certificate')], max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('tuition_range', models.CharField(blank=True, max_length=100)),
                ('career_prospects', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='SupportResource',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sentiment_score',
            new_name='helpfulness_score',
        ),
        migrations.AddField(
            model_name='conversation',
            name='topic_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='related_programs',
            field=models.ManyToManyField(blank=True, to='chatbot.universityprogram'),
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
