# Generated by Django 5.2.5 on 2025-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_admissionresource_careerpath_studentcampaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('application_start_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('entrance_exam_date', models.DateField(blank=True, null=True)),
                ('result_announcement_date', models.DateField(blank=True, null=True)),
                ('admission_start_date', models.DateField(blank=True, null=True)),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requirements', models.TextField()),
                ('documents_needed', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('office_hours', models.CharField(max_length=100)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Admission Information',
            },
        ),
        migrations.CreateModel(
            name='CampusFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('library', 'Library'), ('laboratory', 'Laboratory'), ('hostel', 'Hostel'), ('sports', 'Sports Facility'), ('cafeteria', 'Cafeteria'), ('transport', 'Transportation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('operating_hours', models.CharField(blank=True, max_length=100)),
                ('contact_info', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('office_location', models.CharField(max_length=200)),
                ('office_hours', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('joke', 'Joke'), ('encouragement', 'Encouragement'), ('fun_fact', 'Fun Fact'), ('tip', 'Study Tip'), ('advice', 'Career Advice')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('tone', models.CharField(blank=True, max_length=50)),
                ('context', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('benefit_amount', models.CharField(max_length=100)),
                ('benefit_type', models.CharField(choices=[('tuition_reduction', 'Tuition Reduction'), ('full_tuition', 'Full Tuition Waiver'), ('stipend', 'Monthly Stipend'), ('other', 'Other Benefits')], max_length=50)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_process', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('club_type', models.CharField(choices=[('academic', 'Academic'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('volunteer', 'Volunteer'), ('professional', 'Professional'), ('other', 'Other')], max_length=50)),
                ('advisor', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('meeting_schedule', models.CharField(blank=True, max_length=200)),
                ('membership_requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('academic', 'Academic'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('festival', 'Festival'), ('ceremony', 'Ceremony'), ('workshop', 'Workshop'), ('competition', 'Competition'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('hostel', 'Hostel Fee'), ('application', 'Application Fee'), ('examination', 'Examination Fee'), ('library', 'Library Fee'), ('sports', 'Sports Fee'), ('other', 'Other Fees')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MMK', max_length=10)),
                ('academic_year', models.CharField(max_length=20)),
                ('payment_schedule', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('events', 'Events'), ('facilities', 'Facilities'), ('achievements', 'Achievements'), ('announcements', 'Announcements'), ('entertainment', 'Entertainment')], max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('content_approved', models.BooleanField(default=False)),
                ('moderator_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'University News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AdmissionResource',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='related_programs',
        ),
        migrations.DeleteModel(
            name='StudentCampaign',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='career_prospects',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='tuition_range',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='university',
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='career_paths',
            field=models.TextField(default='Not specified', help_text='Comma-separated career options'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='entry_requirements',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='industry_connections',
            field=models.TextField(blank=True, help_text='Comma-separated industry partners'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='job_prospects',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='salary_range',
            field=models.CharField(default='500k', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='specializations',
            field=models.TextField(blank=True, help_text='Comma-separated specializations'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='subjects',
            field=models.TextField(default=['Civil', 'IT'], help_text='Comma-separated subject list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='level',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('doctorate', 'Doctorate'), ('certificate', 'Certificate')], default='undergraduate', max_length=20),
        ),
        migrations.DeleteModel(
            name='CareerPath',
        ),
    ]
