# Generated by Django 5.2.5 on 2025-08-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_admissioninfo_campusfacility_contactinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprogram',
            name='career_paths',
            field=models.TextField(default='Not specified', help_text='Comma-separated career options'),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='job_prospects',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='universityprogram',
            name='subjects',
            field=models.TextField(default='Not specified', help_text='Comma-separated subject list'),
        ),
    ]
