# Generated by Django 5.2.5 on 2025-08-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_universityprogram_career_paths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='teacher',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
    ]
