# Generated by Django 5.2.5 on 2025-08-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_contactinformation_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EngagementContent',
        ),
    ]
