# Generated by Django 5.2.5 on 2025-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_delete_engagementcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info_type', models.CharField(choices=[('general', 'General Information'), ('leadership', 'Leadership'), ('location', 'Location & Transportation'), ('history', 'History'), ('other', 'Other')], max_length=20)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'University Information',
            },
        ),
        migrations.DeleteModel(
            name='UniversityFee',
        ),
    ]
