# Generated by Django 5.2.5 on 2025-08-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_universityinfo_delete_universityfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityinfo',
            name='info_type',
            field=models.CharField(choices=[('general', 'General Information'), ('rector', 'rector'), ('pro-rector', 'pro-rector'), ('location', 'Location & Transportation'), ('history', 'History'), ('other', 'Other')], max_length=20),
        ),
    ]
