# Generated by Django 5.2.5 on 2025-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_alter_universityinfo_info_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityinfo',
            name='info_type',
            field=models.CharField(choices=[('general', 'General Information'), ('leadership', 'Leadership'), ('location', 'Location & Transportation'), ('history', 'History'), ('other', 'Other')], max_length=20),
        ),
    ]
